#!/bin/sh
FROM alpine
EXEC apk add --no-cache firefox font-noto

cat <<\EOF > image/before-chroot
#!/bin/sh
xdg_runtime="$XDG_RUNTIME_DIR"; display="$WAYLAND_DISPLAY"

[ -z "$xdg_runtime" ] && xdg_runtime='/run/user/1000' && echo "WARNING; could not find XDG_RUNTIME_DIR, using '$xdg_runtime' as default"
[ -z "$display" ] && display='wayland-0' && echo "WARNING; could not find WAYLAND_DISPLAY, using '$display' as default"

touch 'rootfs/tmp/wayland-display'
mount --bind "$xdg_runtime/$display" 'rootfs/tmp/wayland-display'
EOF
chmod +x image/before-chroot

cat <<EOF > image/after-chroot
#!/bin/sh
umount -l 'rootfs/tmp/wayland-display'
EOF
chmod +x image/after-chroot

cat <<\EOF > image/chroot
#!/bin/sh
export XDG_RUNTIME_DIR='/tmp'
export WAYLAND_DISPLAY='wayland-display'
export MOZ_ENABLE_WAYLAND=1

firefox "$@"
EOF
chmod +x image/chroot
